'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class dbo_UrunStockEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=dbo_UrunStockEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property sysdiagrams() As DbSet(Of sysdiagrams)
    Public Overridable Property tbl_kategoriler() As DbSet(Of tbl_kategoriler)
    Public Overridable Property tbl_musteriler() As DbSet(Of tbl_musteriler)
    Public Overridable Property tbl_satislar() As DbSet(Of tbl_satislar)
    Public Overridable Property tbl_urunler() As DbSet(Of tbl_urunler)

End Class
