'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_satislar
    Public Property SATISID As Integer
    Public Property URUN As Nullable(Of Integer)
    Public Property MUSTERI As Nullable(Of Integer)
    Public Property ADET As Nullable(Of Byte)
    Public Property FIYAT As Nullable(Of Decimal)

    Public Overridable Property tbl_musteriler As tbl_musteriler
    Public Overridable Property tbl_urunler As tbl_urunler

End Class
