'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_musteriler
    Public Property MUSTERIID As Integer
    Public Property MUSTERIAD As String
    Public Property MUSTERISOYAD As String

    Public Overridable Property tbl_satislar As ICollection(Of tbl_satislar) = New HashSet(Of tbl_satislar)

End Class
