'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_kategoriler
    Public Property KATEGORIID As Short
    Public Property KATEGORIAD As String

    Public Overridable Property tbl_urunler As ICollection(Of tbl_urunler) = New HashSet(Of tbl_urunler)

End Class
