'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class tbl_urunler
    Public Property URUNID As Integer
    Public Property URUNAD As String
    Public Property MARKA As String
    Public Property URUNKATEGORI As Nullable(Of Short)
    Public Property URUNFIYAT As Nullable(Of Decimal)
    Public Property STOK As Nullable(Of Byte)

    Public Overridable Property tbl_kategoriler As tbl_kategoriler
    Public Overridable Property tbl_satislar As ICollection(Of tbl_satislar) = New HashSet(Of tbl_satislar)

End Class
